[package]
name = "pl_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
project-root = "0.2.2"

[profile.release]
panic = 'abort'

[features]
default = ["debug"]
debug = []
